name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-gstreamer-full-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good openjdk-17-jdk-headless zip unzip
          pip install --user --upgrade buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # تنظيف أي محاولة فاشلة سابقة وبدء بناء جديد
          buildozer android clean
          yes | buildozer android debug
